input_path: /mnt/pretrain/hanzhang/instruction_datasets/0x22almostEvil_ru-riddles-377_subset_default_split_train_instruction.jsonl
output_path: /mnt/pretrain/hanzhang/scorer_results/DeitaQScorer
num_gpu: 2

scorers:
  - name: DeitaQScorer
    model: hkust-nlp/deita-quality-scorer
    max_length: 2048
    batch_size: 2


