input_path: /mnt/pretrain/hanzhang/instruction_datasets/0x22almostEvil_ru-riddles-377_subset_default_split_train_instruction.jsonl
output_path: results/DeitaCScorer
num_gpu: 1

scorers:
  - name: DeitaCScorer
    model: hkust-nlp/deita-complexity-scorer
    max_length: 2048
    batch_size: 32
  



