input_path: ../data_process/example_input.jsonl
output_path: results/DeitaQScorer
num_gpu: 2

scorers:
  - name: DeitaQScorer
    model: hkust-nlp/deita-quality-scorer
    max_length: 2048
    batch_size: 2


