input_path: /mnt/pretrain/hanzhang/instruction_datasets/0x22almostEvil_ru-riddles-377_subset_default_split_train_instruction.jsonl
output_path: /mnt/pretrain/hanzhang/scorer_results/example_output_FailRateScorer
num_gpu: 2

scorers:
  - name: FailRateScorer
    model: Qwen/Qwen3-8B
    metrics_sample_size: 4  # 1, 4, 8, 16, 32, 64
    generation_size: 4096