input_path: ../data_process/example_input_w_answer.jsonl
output_path: results/example_output_FailRateScorer
num_gpu: 2

scorers:
  - name: FailRateScorer
    model: Qwen/Qwen3-8B
    metrics_sample_size: 4  # 1, 4, 8, 16, 32, 64
    generation_size: 4096