input_path: /mnt/pretrain/hanzhang/instruction_datasets/0x70DA_stackoverflow-chat-data_subset_default_split_train_instruction.jsonl
output_path: /mnt/pretrain/hanzhang/scorer_results/example_output_MultiScorer
num_gpu: 2

scorers:
  - name: DeitaCScorer
    model: hkust-nlp/deita-complexity-scorer
    max_length: 2048
    batch_size: 32
  - name: DeitaQScorer
    model: hkust-nlp/deita-quality-scorer
    max_length: 2048
    batch_size: 2
  - name: IFDScorer
    model: Qwen/Qwen2.5-3B-Instruct
    max_length: 2048
  - name: ThinkingProbScorer
    model: THU-KEG/AdaptThink-7B-delta0.05
    batch_size: 128
  - name: SkyworkRewardScorer
    model: Skywork/Skywork-Reward-V2-Llama-3.1-8B-40M
    max_length: 4096
    batch_size: 2
  
