input_path: ../data_process/example_input.jsonl
output_path: results/RewardModel_demo
num_gpu: 2

scorers:
  - name: SkyworkRewardScorer
    model: Skywork/Skywork-Reward-V2-Llama-3.1-8B-40M
    max_length: 4096
    batch_size: 2
