input_path: /mnt/pretrain/hanzhang/instruction_datasets/0x22almostEvil_ru-riddles-377_subset_default_split_train_instruction.jsonl
output_path: /mnt/pretrain/hanzhang/scorer_results/RewardModel_demo
num_gpu: 2

scorers:
  - name: SkyworkRewardScorer
    model: Skywork/Skywork-Reward-V2-Llama-3.1-8B-40M
    max_length: 4096
    batch_size: 2
