input_path: /mnt/pretrain/hanzhang/instruction_datasets/0x22almostEvil_ru-riddles-377_subset_default_split_train_instruction.jsonl
output_path: /mnt/pretrain/hanzhang/scorer_results/example_output_ThinkingProbScorer
num_gpu: 2

scorers:
  - name: ThinkingProbScorer
    model: THU-KEG/AdaptThink-7B-delta0.05
    batch_size: 128
